### ISSUE TITLE
Queries about number of labels

### ISSUE THREAD

**Issue by RupeshGoud** [davidsbatista/text-classification#2]
Hey, thanks for the great article,
Can you please help me by answering below queries?
I have tried the same method using on a dataset which contains more than 400 labels and 7000 is the entire size of the dataset, but I'm not able to get the accurate results as you.
Can you suggest me a better way when there are more labels?
Thanks in advance!!

**Comment by davidsbatista** [comment]
Depends a lot on the problem I guess, if possible explore hierarchical classification methods
